-- Short, human-friendly platform and marketing identifiers.
--
-- Platform IDs and referral codes are deliberately generated by separate
-- server-side functions. A referral code must never be derived from a user
-- UUID or platform ID, and neither identifier is trusted from the browser.

alter table public.profiles
  add column if not exists referral_prompt_completed_at timestamptz;

alter table public.marketing_referral_codes
  alter column sales_person_id drop not null;

alter table public.marketing_referral_codes
  add column if not exists marketing_admin_id uuid references public.profiles (id) on delete cascade;

alter table public.marketing_referral_codes
  drop constraint if exists marketing_referral_codes_owner_check;

alter table public.marketing_referral_codes
  add constraint marketing_referral_codes_owner_check check (
    (sales_person_id is not null and marketing_admin_id is null)
    or (sales_person_id is null and marketing_admin_id is not null)
  );

-- Historical code rows remain available for audit, but only active codes need
-- to be unique. This keeps the finite short-code pools reusable after a
-- deliberate rotation without changing any stored attribution snapshots.
alter table public.marketing_referral_codes
  drop constraint if exists marketing_referral_codes_code_key;
create unique index if not exists marketing_referral_codes_active_code_uidx
  on public.marketing_referral_codes (code) where is_active;

create unique index if not exists marketing_referral_codes_active_admin_idx
  on public.marketing_referral_codes (marketing_admin_id) where is_active;
create index if not exists marketing_referral_codes_admin_idx
  on public.marketing_referral_codes (marketing_admin_id, is_active);

-- Generate an independent U + eight-digit platform identifier.
create or replace function public.generate_unique_platform_id()
returns text
language plpgsql
security definer set search_path = public
as $$
declare
  v_candidate text;
  v_attempt integer;
begin
  perform pg_advisory_xact_lock(hashtext('abrobiz:platform-ids'));
  for v_attempt in 1..1000 loop
    v_candidate := 'U' || lpad(floor(random() * 100000000)::bigint::text, 8, '0');
    if not exists (select 1 from public.profiles where platform_id = v_candidate) then
      return v_candidate;
    end if;
  end loop;
  raise exception 'Could not generate a unique platform ID';
end;
$$;

revoke all on function public.generate_unique_platform_id() from public, anon, authenticated;

-- Existing IDs are migrated to the new public format. Historical audit
-- snapshots remain immutable; profiles receive the new current identifier.
do $$
declare
  v_profile record;
begin
  perform set_config('app.platform_id_migration', 'on', true);
  for v_profile in select id from public.profiles order by created_at, id loop
    update public.profiles
    set platform_id = public.generate_unique_platform_id()
    where id = v_profile.id;
  end loop;
end;
$$;

-- New auth users receive a server-generated platform ID. Keep the existing
-- attribution trigger behavior for email and Google signups.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles as profile (id, platform_id, email, name, phone, email_verified_at, role, admin_role)
  values (
    new.id,
    public.generate_unique_platform_id(),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    case when new.raw_app_meta_data ->> 'provider' = 'google'
      then coalesce(new.email_confirmed_at, now())
      else null
    end,
    case when lower(coalesce(new.email, '')) = 'oneabdre@gmail.com' then 'super_admin' else 'owner' end,
    case when lower(coalesce(new.email, '')) = 'oneabdre@gmail.com' then 'super_admin' else 'none' end
  )
  on conflict (id) do update
    set email = excluded.email,
        email_verified_at = coalesce(profile.email_verified_at, excluded.email_verified_at);
  perform public.create_marketing_attribution(new.id, new.raw_user_meta_data ->> 'referral_code');
  return new;
end;
$$;

-- Keep profile recovery compatible with the new identifier format.
create or replace function public.record_legal_acceptance(
  p_terms_accepted boolean,
  p_privacy_accepted boolean,
  p_legal_version text default '2026-01'
)
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  v_user auth.users%rowtype;
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Not authenticated'; end if;
  if p_terms_accepted is not true or p_privacy_accepted is not true then
    raise exception 'Both legal documents must be accepted';
  end if;
  if p_legal_version is distinct from '2026-01' then
    raise exception 'Unsupported legal version';
  end if;

  select * into v_user from auth.users where id = v_user_id;
  if not found then raise exception 'Authenticated user was not found'; end if;

  insert into public.profiles (id, platform_id, name, phone, email, email_verified_at, role, admin_role)
  values (
    v_user.id,
    public.generate_unique_platform_id(),
    coalesce(v_user.raw_user_meta_data ->> 'name', v_user.raw_user_meta_data ->> 'full_name', ''),
    coalesce(v_user.raw_user_meta_data ->> 'phone', ''),
    coalesce(v_user.email, ''),
    case when v_user.raw_app_meta_data ->> 'provider' = 'google'
      then coalesce(v_user.email_confirmed_at, now())
      else null
    end,
    case when lower(coalesce(v_user.email, '')) = 'oneabdre@gmail.com' then 'super_admin' else 'owner' end,
    case when lower(coalesce(v_user.email, '')) = 'oneabdre@gmail.com' then 'super_admin' else 'none' end
  )
  on conflict (id) do nothing;

  perform set_config('app.legal_acceptance', 'on', true);
  update public.profiles
  set terms_accepted_at = now(),
      privacy_accepted_at = now(),
      legal_version = p_legal_version
  where id = v_user_id;
  if not found then raise exception 'Legal acceptance profile could not be saved'; end if;
  return true;
end;
$$;

-- Add the referral-completion marker to the protected profile-field trigger.
create or replace function public.protect_profile_security_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' and not public.is_super_admin() then
    if current_setting('app.super_admin_bootstrap', true) is distinct from 'on'
      and (
        new.id is distinct from old.id
        or new.email is distinct from old.email
        or new.role is distinct from old.role
        or new.admin_role is distinct from old.admin_role
        or new.email_verified_at is distinct from old.email_verified_at
        or new.marketing_policy_accepted_at is distinct from old.marketing_policy_accepted_at
        or new.marketing_policy_version is distinct from old.marketing_policy_version
      ) then
      raise exception 'Protected profile fields can only be changed through an authorized workflow';
    end if;

    if current_setting('app.platform_id_migration', true) is distinct from 'on'
      and new.platform_id is distinct from old.platform_id then
      raise exception 'Protected profile fields can only be changed through an authorized workflow';
    end if;

    if current_setting('app.referral_prompt_completion', true) is distinct from 'on'
      and new.referral_prompt_completed_at is distinct from old.referral_prompt_completed_at then
      raise exception 'Referral prompt completion must be recorded through the referral workflow';
    end if;

    if current_setting('app.legal_acceptance', true) is distinct from 'on'
      and (
        new.terms_accepted_at is distinct from old.terms_accepted_at
        or new.privacy_accepted_at is distinct from old.privacy_accepted_at
        or new.legal_version is distinct from old.legal_version
      ) then
      raise exception 'Legal acceptance must be recorded through the acceptance flow';
    end if;
  end if;
  return new;
end;
$$;

-- Sales Person codes are SA + three digits. Marketing Admin codes are MA +
-- two digits. Both pools are independent of platform IDs.
create or replace function public.ensure_marketing_referral_code(p_sales_person_id uuid)
returns public.marketing_referral_codes
language plpgsql
security definer set search_path = public
as $$
declare
  v_existing public.marketing_referral_codes;
  v_created public.marketing_referral_codes;
  v_candidate text;
  v_attempt integer;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_sales_person_id and role = 'admin' and admin_role = 'sales_person'
  ) then
    raise exception 'Sales Person not found';
  end if;

  perform pg_advisory_xact_lock(hashtext('abrobiz:short-referral-codes'));

  select * into v_existing
  from public.marketing_referral_codes
  where sales_person_id = p_sales_person_id and is_active
    and code ~ '^SA[0-9]{3}$'
  order by created_at desc limit 1;
  if v_existing.id is not null then return v_existing; end if;

  update public.marketing_referral_codes
  set is_active = false, updated_at = now()
  where sales_person_id = p_sales_person_id and is_active;

  for v_attempt in 1..200 loop
    v_candidate := 'SA' || lpad(floor(random() * 1000)::int::text, 3, '0');
    begin
      insert into public.marketing_referral_codes (sales_person_id, marketing_admin_id, code, label, created_by)
      values (p_sales_person_id, null, v_candidate, 'System-generated Sales Person referral code', auth.uid())
      returning * into v_created;
      return v_created;
    exception when unique_violation then
      -- Retry a code already used by another account or an inactive legacy row.
    end;
  end loop;
  raise exception 'Could not generate a unique Sales Person referral code';
end;
$$;

create or replace function public.ensure_marketing_admin_referral_code(p_marketing_admin_id uuid)
returns public.marketing_referral_codes
language plpgsql
security definer set search_path = public
as $$
declare
  v_existing public.marketing_referral_codes;
  v_created public.marketing_referral_codes;
  v_candidate text;
  v_attempt integer;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_marketing_admin_id
      and role in ('admin', 'super_admin')
      and admin_role = 'marketing_admin'
  ) then
    raise exception 'Marketing Admin not found';
  end if;

  perform pg_advisory_xact_lock(hashtext('abrobiz:short-referral-codes'));

  select * into v_existing
  from public.marketing_referral_codes
  where marketing_admin_id = p_marketing_admin_id and is_active
    and code ~ '^MA[0-9]{2}$'
  order by created_at desc limit 1;
  if v_existing.id is not null then return v_existing; end if;

  update public.marketing_referral_codes
  set is_active = false, updated_at = now()
  where marketing_admin_id = p_marketing_admin_id and is_active;

  for v_attempt in 1..200 loop
    v_candidate := 'MA' || lpad(floor(random() * 100)::int::text, 2, '0');
    begin
      insert into public.marketing_referral_codes (sales_person_id, marketing_admin_id, code, label, created_by)
      values (null, p_marketing_admin_id, v_candidate, 'System-generated Marketing Admin referral code', auth.uid())
      returning * into v_created;
      return v_created;
    exception when unique_violation then
      -- Retry a code already used by another account or an inactive legacy row.
    end;
  end loop;
  raise exception 'Could not generate a unique Marketing Admin referral code';
end;
$$;

revoke all on function public.ensure_marketing_referral_code(uuid) from public, anon, authenticated;
grant execute on function public.ensure_marketing_referral_code(uuid) to service_role;
revoke all on function public.ensure_marketing_admin_referral_code(uuid) from public, anon, authenticated;
grant execute on function public.ensure_marketing_admin_referral_code(uuid) to service_role;

-- Existing long codes are retired and replaced with the new short format.
update public.marketing_referral_codes
set is_active = false, updated_at = now()
where is_active
  and (
    (sales_person_id is not null and code !~ '^SA[0-9]{3}$')
    or (marketing_admin_id is not null and code !~ '^MA[0-9]{2}$')
  );

do $$
declare
  v_row record;
begin
  for v_row in select id from public.profiles where role = 'admin' and admin_role = 'sales_person' loop
    perform public.ensure_marketing_referral_code(v_row.id);
  end loop;
  for v_row in select id from public.profiles where role in ('admin', 'super_admin') and admin_role = 'marketing_admin' loop
    perform public.ensure_marketing_admin_referral_code(v_row.id);
  end loop;
end;
$$;

-- Attribution accepts both short code owners. A Sales Person code also
-- carries the currently assigned Marketing Admin for team commissions; a
-- Marketing Admin code attributes directly to that administrator.
create or replace function public.create_marketing_attribution(
  p_owner_id uuid,
  p_referral_code text default null
)
returns public.marketing_attributions
language plpgsql
security definer set search_path = public
as $$
declare
  v_attribution public.marketing_attributions;
  v_existing public.marketing_attributions;
  v_code public.marketing_referral_codes;
  v_admin_id uuid;
  v_code_text text := nullif(upper(btrim(coalesce(p_referral_code, ''))), '');
begin
  if auth.role() <> 'service_role' and auth.uid() <> p_owner_id then
    raise exception 'Not authorized';
  end if;

  if v_code_text is not null then
    select * into v_code
    from public.marketing_referral_codes
    where code = v_code_text and is_active;

    if v_code.id is not null and v_code.marketing_admin_id is not null then
      if not exists (
        select 1 from public.profiles
        where id = v_code.marketing_admin_id
          and role in ('admin', 'super_admin')
          and admin_role = 'marketing_admin'
      ) then
        v_code.id := null;
      end if;
    elsif v_code.id is not null then
      select marketing_admin_id into v_admin_id
      from public.marketing_team_memberships
      where sales_person_id = v_code.sales_person_id and ended_at is null
      order by started_at desc limit 1;
      if not exists (
        select 1 from public.profiles
        where id = v_code.sales_person_id
          and role = 'admin'
          and admin_role = 'sales_person'
      ) then
        v_code.id := null;
      end if;
    end if;
  end if;

  select * into v_existing
  from public.marketing_attributions
  where owner_id = p_owner_id
  for update;

  if found then
    -- Only complete the direct attribution created by the auth trigger. An
    -- existing referral or administrator correction remains immutable.
    if v_existing.source = 'direct'
       and v_code.id is not null
       and (
         current_setting('app.google_referral_completion', true) = 'on'
         or exists (
           select 1 from auth.users u
           where u.id = p_owner_id
             and u.created_at >= now() - interval '10 minutes'
         )
       ) then
      update public.marketing_attributions
      set sales_person_id = case when v_code.marketing_admin_id is null then v_code.sales_person_id else null end,
          marketing_admin_id = case
            when v_code.marketing_admin_id is not null then v_code.marketing_admin_id
            else v_admin_id
          end,
          referral_code_id = v_code.id,
          referral_code_snapshot = v_code.code,
          source = 'referral_code',
          attribution_status = 'locked',
          locked_at = now(),
          updated_at = now()
      where id = v_existing.id
      returning * into v_attribution;

      insert into public.marketing_attribution_events (
        attribution_id, owner_id,
        old_sales_person_id, old_marketing_admin_id,
        new_sales_person_id, new_marketing_admin_id,
        reason
      ) values (
        v_attribution.id, p_owner_id,
        v_existing.sales_person_id, v_existing.marketing_admin_id,
        v_attribution.sales_person_id, v_attribution.marketing_admin_id,
        'Referral attribution completed after Google signup'
      );
      return v_attribution;
    end if;
    return v_existing;
  end if;

  insert into public.marketing_attributions (
    owner_id, sales_person_id, marketing_admin_id, referral_code_id,
    referral_code_snapshot, source
  ) values (
    p_owner_id,
    case when v_code.id is null or v_code.marketing_admin_id is not null then null else v_code.sales_person_id end,
    case when v_code.id is null then null
      when v_code.marketing_admin_id is not null then v_code.marketing_admin_id
      else v_admin_id
    end,
    case when v_code.id is null then null else v_code.id end,
    case when v_code.id is null then null else v_code.code end,
    case when v_code.id is null then 'direct' else 'referral_code' end
  )
  returning * into v_attribution;

  insert into public.marketing_attribution_events (
    attribution_id, owner_id, new_sales_person_id, new_marketing_admin_id, reason
  ) values (
    v_attribution.id, p_owner_id, v_attribution.sales_person_id,
    v_attribution.marketing_admin_id,
    case when v_attribution.sales_person_id is null and v_attribution.marketing_admin_id is null
      then 'Direct registration'
      else 'Referral registration'
    end
  );
  return v_attribution;
end;
$$;

revoke all on function public.create_marketing_attribution(uuid, text) from public;
grant execute on function public.create_marketing_attribution(uuid, text) to authenticated, service_role;

-- Role assignment remains super-admin-only while ensuring role holders receive
-- the correct code and demoted users lose active referral links.
create or replace function public.super_admin_assign_admin_role(
  p_user_id uuid,
  p_admin_role text
)
returns public.profiles
language plpgsql
security definer set search_path = public
as $$
declare
  v_profile public.profiles;
  v_old_role text;
  v_old_admin_role text;
  v_role text;
begin
  if not public.is_super_admin() then raise exception 'Super administrators only'; end if;
  if p_user_id is null or p_user_id = auth.uid() then raise exception 'You cannot change your own administrator role'; end if;
  if p_admin_role not in ('none', 'super_admin', 'operations', 'support', 'finance', 'content', 'marketing_admin', 'sales_person') then
    raise exception 'Invalid administrator role';
  end if;
  if exists (
    select 1 from public.profiles
    where id = p_user_id and lower(email) = 'oneabdre@gmail.com'
  ) and p_admin_role <> 'super_admin' then
    raise exception 'The AbroBiz platform owner must remain a super administrator';
  end if;
  select * into v_profile from public.profiles where id = p_user_id for update;
  if v_profile.id is null then raise exception 'User not found'; end if;

  v_old_role := v_profile.role;
  v_old_admin_role := v_profile.admin_role;
  v_role := case when p_admin_role = 'none' then 'owner' when p_admin_role = 'super_admin' then 'super_admin' else 'admin' end;

  update public.profiles
  set role = v_role, admin_role = p_admin_role
  where id = p_user_id
  returning * into v_profile;

  if p_admin_role = 'sales_person' then
    perform public.ensure_marketing_referral_code(p_user_id);
  elsif p_admin_role = 'marketing_admin' then
    perform public.ensure_marketing_admin_referral_code(p_user_id);
  end if;

  if v_old_admin_role = 'sales_person' and p_admin_role <> 'sales_person' then
    update public.marketing_referral_codes set is_active = false, updated_at = now()
    where sales_person_id = p_user_id and is_active;
    update public.marketing_team_memberships set ended_at = coalesce(ended_at, now())
    where sales_person_id = p_user_id and ended_at is null;
  elsif v_old_admin_role = 'marketing_admin' and p_admin_role <> 'marketing_admin' then
    update public.marketing_referral_codes set is_active = false, updated_at = now()
    where marketing_admin_id = p_user_id and is_active;
    update public.marketing_team_memberships set ended_at = coalesce(ended_at, now())
    where marketing_admin_id = p_user_id and ended_at is null;
  end if;

  insert into public.admin_logs (admin_id, action, target_table, target_id, meta)
  values (
    auth.uid(), 'assign_admin_role', 'profiles', p_user_id,
    jsonb_build_object('from_role', v_old_role, 'from_admin_role', v_old_admin_role,
      'to_role', v_role, 'to_admin_role', p_admin_role,
      'target_platform_id', v_profile.platform_id)
  );
  return v_profile;
end;
$$;

revoke all on function public.super_admin_assign_admin_role(uuid, text) from public;
grant execute on function public.super_admin_assign_admin_role(uuid, text) to authenticated, service_role;

create or replace function public.super_admin_rotate_marketing_admin_referral_code(p_marketing_admin_id uuid)
returns public.marketing_referral_codes
language plpgsql
security definer set search_path = public
as $$
declare
  v_code public.marketing_referral_codes;
begin
  if not public.is_super_admin() then raise exception 'Super administrators only'; end if;
  update public.marketing_referral_codes
  set is_active = false, updated_at = now()
  where marketing_admin_id = p_marketing_admin_id and is_active;
  select * into v_code from public.ensure_marketing_admin_referral_code(p_marketing_admin_id);
  insert into public.admin_logs (admin_id, action, target_table, target_id, meta)
  values (auth.uid(), 'rotate_marketing_admin_referral_code', 'marketing_referral_codes', v_code.id,
    jsonb_build_object('marketing_admin_id', p_marketing_admin_id));
  return v_code;
end;
$$;

revoke all on function public.super_admin_rotate_marketing_admin_referral_code(uuid) from public;
grant execute on function public.super_admin_rotate_marketing_admin_referral_code(uuid) to authenticated;

-- Complete Google referral onboarding for the authenticated owner. The same
-- endpoint handles an explicit code and a safe skip, and is idempotent.
create or replace function public.complete_google_referral_prompt(p_referral_code text default null)
returns public.marketing_attributions
language plpgsql
security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles;
  v_attribution public.marketing_attributions;
  v_code text := nullif(upper(btrim(coalesce(p_referral_code, ''))), '');
begin
  if v_user_id is null then raise exception 'Not authenticated'; end if;
  if not exists (
    select 1 from auth.users
    where id = v_user_id and coalesce(raw_app_meta_data ->> 'provider', '') = 'google'
  ) then
    raise exception 'Google referral onboarding is only available for Google accounts';
  end if;
  select * into v_profile from public.profiles where id = v_user_id for update;
  if v_profile.id is null then raise exception 'Account profile not found'; end if;
  -- A returning administrator can still use the Google button from the
  -- registration screen without being forced through owner onboarding.
  if v_profile.role <> 'owner' then
    select * into v_attribution from public.marketing_attributions where owner_id = v_user_id;
    return v_attribution;
  end if;

  if v_profile.referral_prompt_completed_at is not null then
    select * into v_attribution from public.marketing_attributions where owner_id = v_user_id;
    return v_attribution;
  end if;

  if v_code is not null then
    if v_code !~ '^(SA[0-9]{3}|MA[0-9]{2})$'
       or not exists (select 1 from public.marketing_referral_codes where code = v_code and is_active) then
      raise exception 'Enter a valid active referral code or choose Skip';
    end if;
  end if;

  perform set_config('app.google_referral_completion', 'on', true);
  select * into v_attribution from public.create_marketing_attribution(v_user_id, v_code);
  perform set_config('app.referral_prompt_completion', 'on', true);
  update public.profiles
  set referral_prompt_completed_at = now()
  where id = v_user_id;
  return v_attribution;
end;
$$;

revoke all on function public.complete_google_referral_prompt(text) from public, anon;
grant execute on function public.complete_google_referral_prompt(text) to authenticated;

-- An already completed Google account should not be shown a new-user prompt
-- after rollout. Accounts created after this migration retain NULL until they
-- choose a code or Skip.
do $$
begin
  perform set_config('app.referral_prompt_completion', 'on', true);
  update public.profiles p
  set referral_prompt_completed_at = coalesce(p.referral_prompt_completed_at, u.created_at, now())
  from auth.users u
  where u.id = p.id
    and coalesce(u.raw_app_meta_data ->> 'provider', '') = 'google'
    and p.referral_prompt_completed_at is null;
end;
$$;

-- Make referral-code visibility work for both code owners while retaining the
-- existing team-scoped access model.
drop policy if exists marketing_referral_codes_select on public.marketing_referral_codes;
create policy marketing_referral_codes_select on public.marketing_referral_codes
  for select using (
    sales_person_id = auth.uid()
    or marketing_admin_id = auth.uid()
    or public.is_super_admin()
    or public.has_admin_permission('marketing.manage')
    or exists (
      select 1 from public.marketing_team_memberships tm
      where tm.sales_person_id = marketing_referral_codes.sales_person_id
        and tm.marketing_admin_id = auth.uid()
        and tm.ended_at is null
    )
  );

drop policy if exists marketing_referral_codes_write on public.marketing_referral_codes;
create policy marketing_referral_codes_write on public.marketing_referral_codes
  for all using (
    public.is_super_admin()
    or public.has_admin_permission('marketing.manage')
    or (sales_person_id = auth.uid() and public.has_admin_permission('marketing.referrals'))
  ) with check (
    public.is_super_admin()
    or public.has_admin_permission('marketing.manage')
    or (sales_person_id = auth.uid() and public.has_admin_permission('marketing.referrals'))
  );
